### ISSUE TITLE
Create installers for CLI Tool

### ISSUE THREAD

**Issue by unnamedd** [QuarkX/Quark#11]
The main goal is to create four new ways to install the Quark CLI Tool:
- [ ] cURL shell script
- [ ] brew 
- [ ] apt-get 
- [ ] Package Installer

**Comment by paulofaria** [comment]
@unnamedd Aptana is a typo for `apt-get`?

**Comment by unnamedd** [comment]
Yes @paulofaria!

**Comment by Lidbetter** [comment]
Until a tagged version of the Tool is released, here is the homebrew fomula:
https://github.com/QuarkX/homebrew-tap

Once a a version is tagged the formula can be moved into the homebrew core (the tap will not be required)
