### ISSUE TITLE
Add contribution information

### ISSUE THREAD

**Issue by Danappelxx** [QuarkX/Quark#14]
Includes [code of conduct](https://github.com/Zewo/Zewo/blob/master/CODEOFCONDUCT.md) and [contribution guidelines](https://github.com/Zewo/Zewo/blob/master/CONTRIBUTING.md).

We should make it very clear in the readme that after you submit a pr or two, you will receive an invite to the organization, though there is no pressure to contribute.

**Comment by paulofaria** [comment]
fixed by 1f3f4ae!
