### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by Danappelxx** [QuarkX/Quark#24]
Currently we have 0% test coverage, which is quite shameful considering we have a load of unit tests from Zewo and earlier which just haven't been updated. For example, in its earlier versions, [Venice](https://github.com/VeniceX/Venice/tree/v0.9) had 99% test coverage!

**Comment by paulofaria** [comment]
I think we should set 25%+ as the goal for 0.1.0. What do you think?

**Comment by paulofaria** [comment]
Closing this with 95% test coverage! (:
