### ISSUE TITLE
Update modules from Zewo to latest versions

### ISSUE THREAD

**Issue by Danappelxx** [QuarkX/Quark#3]
Some modules are missing out on critical bug fixes. For example, HTTPParser is missing [a fix](https://github.com/Zewo/HTTPParser/commit/0e4dbeb1ea203a5fc0f575f1bcc2c2a2b005010c) that would cause it to crash on certain edge cases.

**Comment by paulofaria** [comment]
Which modules need fix?

**Comment by Danappelxx** [comment]
Well, there's no indication of how old these modules are but the HTTPParser in Quark still has implicitly unwrapped optionals, so at the very least all fixes from the past 11 days
